name: UI CI

on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ci-ui.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'ui/**'
      - '.github/workflows/ci-ui.yml'

jobs:
  build-and-test-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ui
        run: npm install

      - name: Lint & Test
        working-directory: ui
        run: |
          npm run lint
          npm test
